urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Home
    url(r'^$', 'election.views.index'),
    url(r'^ro_home.html$', 'election.views.ro_homepage'),
    url(r'^eo_home.html$', 'election.views.eo_homepage'),
    url(r'^reporter_home.html$', 'election.views.reporter_homepage'),
    url(r'^admin_home.html$', 'election.views.admin_homepage'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', 'election.views.logout_user'),
    
    url(r'^users/$', 'users.views.index'),
    url(r'^users/add/$', 'users.views.add_user'),
    url(r'^users/(\d+)/$', 'users.views.view_user'),
    url(r'^users/(\d+)/modify/$', 'users.views.modify_user'),
    url(r'^users/(\d+)/ban/$', 'users.views.ban_user'),
    url(r'^users/(\d+)/delete/$', 'users.views.delete_user'),

    url(r'^election/recount/$', 'election.views.start_recount'),
    url(r'^election/change-status/$', 'election.views.change_election_status'),
    url(r'^election/change/$', 'election.views.change_election'),
    url(r'^election/location/$', 'election.views.set_location'),
    url(r'^election/winners/(\d+)/$', 'election.views.calc_winners'),
    url(r'^election/all_winners/$', 'election.views.calc_all_winners'),
    url(r'^election/save/$', 'election.views.save_db'),
    url(r'^election/restart/$', 'election.views.reset_db'),
    url(r'^election/clear/$', 'election.views.reset_db_full'),
    url(r'^election/choose-riding/$', 'ridings.views.choose_riding'),

    url(r'^ballots/$', 'ballots.views.view_ballots'),
    url(r'^ballots/add/poll/$', 'ballots.views.choose_poll'),
    url(r'^ballots/add/(\d+)/$', 'ballots.views.input_ballot'),
    url(r'^ballots/add/tiebreaker/(\d+)/$', 'ballots.views.input_ballot_tiebreaker'),
    url(r'^ballots/(\d+)/$', 'ballots.views.view_ballot'),
    url(r'^ballots/verify/choose/$', 'ballots.views.choose_riding_to_verify'),
    url(r'^ballots/verify/riding/(\d+)/$', 'ballots.views.verify_riding'),
    url(r'^ballots/compare_ballot/(\d+)/$', 'ballots.views.compare_ballot'),
    url(r'^ballots/accept_ballot/$', 'ballots.views.accept_ballot'),
    url(r'^ballots/auto_accept_ballot/(\d+)/$', 'ballots.views.auto_accept_ballot'),

    url(r'^politicians/$', 'politicians.views.view_all_politicians'),
    url(r'^politicians/(\d+)/$', 'politicians.views.view_politician'),
    url(r'^politicians/(\d+)/modify/$', 'politicians.views.modify_politician'),
    url(r'^politicians/add/$', 'politicians.views.add_politician'),
    url(r'^politicians/add/(\d+)/$', 'politicians.views.add_politician_keyword'),

    url(r'^ridings/$', 'ridings.views.view_all_ridings'),
    url(r'^ridings/add/$', 'ridings.views.add_riding'),
    url(r'^ridings/add/(\d+)/$', 'ridings.views.add_riding_keyword'),
    url(r'^ridings/(\d+)/$', 'ridings.views.view_riding'),
    url(r'^ridings/(\d+)/modify/$', 'ridings.views.modify_riding'),
    url(r'^ridings/(\d+)/polls/$', 'ridings.views.view_polls'),
    url(r'^ridings/(\d+)/polls/(\d+)/close/$', 'ridings.views.close_poll'),
    url(r'^ridings/(\d+)/polls/add/$', 'ridings.views.add_poll'),
    url(r'^ridings/(\d+)/polls/(\d+)/modify/$', 'ridings.views.modify_poll'),

    url(r'^keywords/$', 'keywords.views.index'),
    url(r'^keywords/assign/(riding|politician)/$', 'keywords.views.assign_keyword_value'),
    url(r'^keywords/riding/add/$', 'keywords.views.new_riding_keyword'),
    url(r'^keywords/riding/values/(\d+)/$', 'keywords.views.new_riding_keyword_value'),
    url(r'^keywords/politician/add/$', 'keywords.views.new_politician_keyword'),
    url(r'^keywords/politician/values/(\d+)/$', 'keywords.views.new_politician_keyword_value'),
    url(r'^keywords/riding/(\d+)/modify/$', 'keywords.views.edit_riding_keyword'),
    url(r'^keywords/riding/modify/values/(\d+)/$', 'keywords.views.edit_riding_keyword_value'),
    url(r'^keywords/politician/(\d+)/modify/$', 'keywords.views.edit_politician_keyword'),
    url(r'^keywords/politician/modify/values/(\d+)/$', 'keywords.views.edit_politician_keyword_value'),
    url(r'^keywords/riding/restore/$', 'keywords.views.restoreRidingKeyword'),
    url(r'^keywords/politician/restore/$', 'keywords.views.restorePoliticianKeyword'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ballots/models.py
from django.db import models
from django import forms
from ridings.models import Poll, Riding
from politicians.models import Politician
from jsonfield import JSONField
from django.forms import ModelForm
from django.contrib.auth.models import User
import json
from django.db import IntegrityError

BALLOT_STATE_CHOICES = (
    ('U', 'Unverified'),
    ('C', 'Correct'),
    ('I', 'Incorrect'),
    ('R', 'Recount'),
)
# State machine:
# U -> C
# U -> I
# (U,C,I) -> R

class Ballot(models.Model):
    
    ballot_num = models.IntegerField(db_index=True)
    poll = models.ForeignKey(Poll, db_index=True)
    # State of ballot for verification
    state = models.CharField(max_length=1, choices=BALLOT_STATE_CHOICES, default='U', null=False, db_index=True)
    # Was the ballot spoiled/rejected?
    spoiled = models.BooleanField(default=False, db_index=True)
    # Vote will store a list of ranking: candidate pairs
    # JSONField will not load back properly, and we are decoding the contents anyway
    vote = models.TextField(blank=True,help_text="Contents of ballot, JSON as a string")
    entered_by = models.ForeignKey(User, null=True, blank=True, db_index=True,help_text="Which RO entered the ballot")
    ballot_hash = models.CharField(max_length=128, null=True, blank=True)
    

    def __unicode__(self):
        return unicode(self.ballot_num)+", "+unicode(self.state)+", "+unicode(self.vote)

    def candidates_as_string(self):
        nice_string=[]
        candidates = Politician.objects.filter(candidate_riding=self.poll.riding)
        vote_json=json.loads(self.vote)
        for (k,v) in sorted(vote_json.iteritems(), key=lambda x:x[0]):
            if len(v)>0:
                candidate=candidates.get(id=int(v))
                nice_string.append("#"+str(k)+": "+candidate.name)
        return ", ".join(nice_string)

    def save(self, *args, **kwargs):
        if 'current_ro' in kwargs:
            me=kwargs['current_ro']
            conflicting_ballots=Ballot.objects.filter(ballot_num=self.ballot_num).filter(entered_by=me)
            if self.id is not None:
                conflicting_ballots=conflicting_ballots.exclude(id=self.id)
                if me==self.entered_by:
                    raise IntegrityError('You cannot verify a ballot you have entered.')
            if len(conflicting_ballots)>0:
                raise IntegrityError('You have already entered this ballot.')
            del kwargs['current_ro']

        super(Ballot, self).save(*args, **kwargs)
        

def ids_sequential_and_start_at_1(lst):
    return set(lst) == set(range(1,len(lst)+1))
            

class BallotForm(ModelForm):

    def clean_vote(self):
        if 'vote' not in self.cleaned_data:
            raise forms.ValidationError("(clean_vote) vote missing from form input: ")
        try:
            if isinstance(self.cleaned_data['vote'], dict):
                vote_data = self.cleaned_data['vote']
            elif isinstance(self.cleaned_data['vote'], basestring):
                vote_data = json.loads(self.cleaned_data['vote'])
            vote = map(int, vote_data.keys())
            if len(vote) > 0 and not ids_sequential_and_start_at_1(vote):
                raise forms.ValidationError("Non-sequential vote entered.")
        except forms.ValidationError as e:
            raise e
        except Exception as e:
            raise forms.ValidationError("(clean_vote) Could not parse vote data: "+ str(e))
        return json.dumps(vote_data)


    def clean(self):
        cleaned_data = super(BallotForm, self).clean()
        got_vote = True
        # This is still messy
        if 'vote' not in cleaned_data:
            got_vote = False
            pass
        elif isinstance(cleaned_data['vote'], dict):
            vote_data = cleaned_data['vote']
        elif isinstance(cleaned_data['vote'], basestring):
            try:
                v = cleaned_data['vote']
                vote_data=json.loads(v)
            except forms.ValidationError as e:
                raise e
            except Exception as e:
                raise forms.ValidationError("(clean) Could not parse vote data: "+ str(e))
            
        has_values=bool([a for a in vote_data.values() if a != ''])
        if got_vote and not (has_values or cleaned_data['spoiled']):
            raise forms.ValidationError("Invalid ballot: Empty but not spoiled?")
        if cleaned_data['spoiled']:
            cleaned_data['vote'] = {}
        if 'vote' in cleaned_data and isinstance(cleaned_data['vote'], dict):
            cleaned_data['vote'] = json.dumps(cleaned_data['vote'])
        return cleaned_data
    
    class Meta:
        model = Ballot
        fields = ('poll', 'ballot_num', 'vote', 'spoiled')
        hidden = ('vote')

class ChoosePollForm(forms.Form):
    poll = forms.ModelChoiceField(Poll.objects.filter(delete=False).filter(riding__delete=False))

class ChooseRidingToVerifyForm(forms.Form):
    riding = forms.ModelChoiceField(Riding.objects.filter(delete=False))

class AcceptBallotForm(forms.Form):
    ballot = forms.ModelChoiceField(Ballot.objects.all())

# Very similar to a BallotForm
# but ballot_num and poll are immutable!
class LockedBallotForm(BallotForm):
    def __init__(self,  *args, **kwargs):
        super(LockedBallotForm, self).__init__(*args, **kwargs)
        # Stop users from changing on form
        self.fields['ballot_num'].widget.attrs['readonly'] = True
        self.fields['poll'].widget.attrs['readonly'] = True

    # if they inject it, ignore anyway
    #def clean_poll(self):
    #    return self.instance.poll

    ## if they inject it, ignore anyway
    #def clean_ballot_num(self):
    #    return self.instance.ballot_num

templates/ballots/add.html
{% extends "base.html" %}

{% block h1 %}Add Ballot{% endblock %}

{% block subbreadcrumbs %}
<li><a href="{% url ballots.views.choose_poll %}">Choose Poll</a></li>
<li>Enter Ballot for Poll {{ poll.poll_num }}</li>{% endblock %}
{% block content %}
	    <script src="/static/jquery.js"></script>
	    <script src="/static/json2.js"></script>
        <script src="/static/ballot.js"></script>

<form action="{% url ballots.views.input_ballot form.poll.value %}" method="post" id="myform">
{% csrf_token %}
{{form.non_field_errors}}
{{form.vote.errors}}
{{form.ballot_num.errors}}
{{form.ballot_num.label}}:{{form.ballot_num}}

<table>
	<tr>
		<th>Candidate</th>
		<th colspan="3">Ranking</th>
	</tr>
	<tr>
		<th class="minor_th"></th>
        {% for person in candidates %}
	    	<th class="minor_th">{{forloop.counter}}</th>
        {%endfor%}
	</tr>

	{% for person in candidates %}
	<tr>
		<td>{{ person.name }}</td>
        {%for _ in candidates %}
        	<td><input type="radio" name="{{ person.id }}" class="data-column-{{forloop.counter}}" value="{{forloop.counter}}" /></td>
        {%endfor%}

	</tr>
	{% endfor %}

</table>
{{ form.poll.as_hidden }}
{{ form.vote.as_hidden }}
{{ form.spoiled.errors }}
{{ form.spoiled.label }} :{{ form.spoiled }}
<br />
<input type="submit" value="Submit" />
<input type="reset" value="Clear" />
</form>
        
        <script>
			$("input[type=radio]").click(function(){ enforceBallotValidity(this, '#myform'); });
			$('#myform').submit(onSubmit);
		</script>

{% endblock %}


templates/ballots/choose_poll.html
{% extends "base.html" %}

{% block h1 %}Add Ballot{% endblock %}

{% block subbreadcrumbs %}
<li>Choose Poll</li>
{% endblock %}
{% block content %}


<form
action="" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Enter Ballots" />
</form> 
{% endblock %}


templates/ballots/choose_riding_to_verify.html
{% extends "base.html" %}

{% block h1 %}Choose Riding to Verify{% endblock %}

{% block subbreadcrumbs %}
<li>Choose Riding To Verify</li>
{% endblock %}
{% block content %}


<form
action="" method="post">
{% csrf_token %}
{{ form }}
<input type="submit" value="Select Riding" />
</form> 
{% endblock %}



templates/ballots/compare.html
{% extends "base.html" %}

{% block h1 %}Ballot Conflict Resolution{% endblock %}

{% block subbreadcrumbs %}
<li><a href="{% url ballots.views.choose_riding_to_verify %}">Choose Riding to Verify</a></li>
<li><a href="{% url ballots.views.verify_riding ballots.0.poll.riding.id %}">Conflicted Ballots</a></li>
<li>Resolve Conflict</li>
{% endblock %}

{% block content %}
	    <script src="/static/jquery.js"></script>
	    <script src="/static/json2.js"></script>
        <script src="/static/ballot.js"></script>
     
<table>

<tr class="fake">
<th>RO</th>
<th>Ballot Number</th>
<th>Id</th>
<th>Vote</th>
<th>Choose wisely...</th>
</tr>
{% for ballot in ballots %}
<tr class="fake">
<td>{{ballot.entered_by}}</td>
<td>{{ballot.ballot_num}}</td>
<td>{{ballot.id}}</td>
<td>
<!--This is a fake form.-->
<form id="ballot-{{ballot.id}}" class="fake">
<table>
	<tr>
		<th>Candidate</th>
		<th colspan="3">Ranking</th>
	</tr>
	<tr>
		<th></th>
        {% for person in candidates %}
	    	<th>{{forloop.counter}}</th>
        {%endfor%}
	</tr>

	{% for person in candidates %}
	<tr>
		<td>{{ person.name }}</td>
        {%for _ in candidates %}
        	<td><input type="radio" name="{{person.id}}" class="data-column-{{forloop.counter}}" value="{{forloop.counter}}" id="id-{{person.id}}-{{forloop.counter}}" disabled /></td>
        {%endfor%}
	</tr>
	{% endfor %}
    <td>Spoiled : {{ballot.spoiled}}</td>

</table>
<script>
	display({{ballot.id}}, {{ballot.vote|safe}}, {{ballot.spoiled|lower}});
</script>
</form>
</td>
<td>
<form method="post" id="submit-ballot-{{ballot.id}}" action="{% url ballots.views.accept_ballot %}">
{% csrf_token %}
<input type="submit" value="Use This One" name="{{ballot.ballot_num}}" id="id-{{ballot.ballot_num}}" />
<input type="hidden" name="ballot" value="{{ballot.id}}" />
</form>
</td>
{% endfor %}
</tr>
<!-- End of ballot selection menu -->

<tr>
<td colspan="3">Create new ballot as infaliable 3rd RO</td>
<td>
	<div id="new-ballot-placeholder">
		<i>Select new ballot to display ballot form.</i>
	</div>
	<div id="new-ballot">
<form action="{% url ballots.views.input_ballot_tiebreaker tiebreaker_form.ballot_num.value %}" method="post" id="new-ballot">
{% csrf_token %}
{{tiebreaker_form.non_field_errors}}
{{tiebreaker_form.vote.errors}}
{{tiebreaker_form.ballot_num.errors}}
{{tiebreaker_form.ballot_num.label}}:{{tiebreaker_form.ballot_num}}

<table>
	<tr>
		<th>Candidate</th>
		<th colspan="3">Ranking</th>
	</tr>
	<tr>
		<th></th>
        {% for person in candidates %}
	    	<th>{{forloop.counter}}</th>
        {%endfor%}
	</tr>

	{% for person in candidates %}
	<tr>
		<td>{{ person.name }}</td>
        {%for _ in candidates %}
        	<td><input type="radio" name="{{ person.id }}" class="data-column-{{forloop.counter}}" value="{{forloop.counter}}" /></td>
        {%endfor%}

	</tr>
	{% endfor %}

</table>
{{ tiebreaker_form.poll.as_hidden }}
{{ tiebreaker_form.vote.as_hidden }}
{{ tiebreaker_form.spoiled.errors }}
{{ tiebreaker_form.spoiled.label }} :{{ tiebreaker_form.spoiled }}
<br />
<input type="submit" value="Submit" />
<input type="reset" value="Clear" />
        <script>
			$("form#new-ballot input[type=radio]").click(function(){enforceBallotValidity(this, "form#new-ballot");});
			$('form#new-ballot').submit(onSubmit);
		</script>
</form>
</div>

</td>
<td><input type="button" value="Display New Ballot Form" name="-1" id="display-new-ballot-form" /></td>
</tr>

<script>
	$('#new-ballot').hide();
	$('#display-new-ballot-form').click(function(x){
		$('#new-ballot-placeholder').hide();
		$('#new-ballot').show();
		$('.fake').hide();
		$('#display-new-ballot-form').hide();
	});
</script>


</table>
{% endblock %}

templates/ballots/view.html
{% extends "base.html" %}

{% block h1 %}List of Ballots{% endblock %}

{% block subbreadcrumbs %}
<li><a href="{% url ballots.views.choose_poll %}">Choose Poll</a></li>
<li>List of Ballots</li>
{% endblock %}

{% block content %}
<table>
<tr>
<th>Ballot Number</th>
<th>Poll</th>
<th>State</th>
</tr>

{% for ballot in ballots %}
<tr>
<td><a href="{% url ballots.views.view_ballot ballot.id %}">{{ballot.ballot_num}}</a></td>
<td>{{ballot.poll}}</td>
<td>{{ballot.get_state_display}}</td>
</tr>
{% endfor %}
</table>

{% endblock %}

templates/ballots/view_conflicts.html
{% extends "base.html" %}

{% block h1 %}List of Conflicted Ballots{% endblock %}

{% block subbreadcrumbs %}
<li><a href="{% url ballots.views.choose_riding_to_verify %}">Choose Riding To Verify</a></li>
<li>Conflicted Ballots</li>
{% endblock %}
{% block content %}

{% if single_entry %}
<h2>Ballots with problems: Single Entry</h2>
<table class="ballot_verification">
    <tr>
        <th>Ballot #</th>
        <th>Poll</th>
        <th>Vote Data</th>
        <th>Resolve</th>
    </tr>
    {% for ballot in single_entry %}
        <tr>
            <td>{{ballot.ballot_num}}</td>
            <td>{{ballot.poll}}</td>
            <td>
                {% if ballot.spoiled %}
                    Spoiled
                {% else %}
                    {{ballot.candidates_as_string}}
            {% endif %}</td>
            <td><a href="{% url ballots.views.compare_ballot ballot.id %}">Compare</a></td>
        </tr>
    {% endfor %}
</table>
{% else %}
	<h2>No ballots only entered once.</h2>
{% endif %}

{% if auto_ballots %}
<h2>Ballots eligible for automatic verification</h2>
<table class="ballot_verification">
    <tr>
        <th>Ballot #</th>
        <th>Poll</th>
        <th>Vote Data</th>
        <th>Resolve</th>
    </tr>
    {% for ballot in auto_ballots %}
    <tr>
        <td>{{ballot.ballot_num}}</td>
        <td>{{ballot.poll}}</td>
        <td>
            {% if ballot.spoiled %}
                Spoiled
            {% else %}
                {{ballot.candidates_as_string}}
        {% endif %}</td>
        <td><a href="{% url ballots.views.auto_accept_ballot ballot.id %}">Accept</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
	<h2>No ballots eligible for automatic verification</h2>
{% endif %}

{% if manual_ballots %}
<h2>Ballots requiring manual verification</h2>
<table class="ballot_verification">
    <tr>
        <th>Ballot #</th>
        <th>Poll</th>
        <th>Vote Data</th>
        <th>Resolve</th>
    </tr>
    {% for ballot in manual_ballots %}
    <tr>
        <td>{{ballot.ballot_num}}</td>
        <td>{{ballot.poll}}</td>
        <td>
            {% if ballot.spoiled %}
                Spoiled
            {% else %}
                {{ballot.candidates_as_string}}
        {% endif %}</td>
        <td><a href="{% url ballots.views.compare_ballot ballot.id %}">Compare</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
	<h2>No ballots requiring manual verification</h2>
{% endif %}

{% if invalid_state_mix %}
<h2>Ballots with problems: Invalid State Mix</h2>
<table class="ballot_verification">
    <tr>
        <th>Ballot #</th>
        <th>Poll</th>
        <th>Vote Data</th>
        <th>Resolve</th>
    </tr>
    {% for ballot in invalid_state_mix %}
    <tr>
        <td>{{ballot.ballot_num}}</td>
        <td>{{ballot.poll}}</td>
        <td>
            {% if ballot.spoiled %}
                Spoiled
            {% else %}
                {{ballot.candidates_as_string}}
        {% endif %}</td>
        <td><a href="{% url ballots.views.compare_ballot ballot.id %}">Add Another</a></td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if single_ro_only %}
<h2>Ballots with problems: Single RO Only</h2>
<table class="ballot_verification">
    <tr>
        <th>Ballot #</th>
        <th>Poll</th>
        <th>Vote Data</th>
        <th>Resolve</th>
    </tr>
    {% for ballot in single_ro_only %}
    <tr>
        <td>{{ballot.ballot_num}}</td>
        <td>{{ballot.poll}}</td>
        <td>
            {% if ballot.spoiled %}
                Spoiled
            {% else %}
                {{ballot.candidates_as_string}}
        {% endif %}</td>
            <td><a href="{% url ballots.views.compare_ballot ballot.id %}">Add Another</a></td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}

templates/ballots/view_single.html
{% extends "base.html" %}

{% block h1 %}Ballot {{ ballot.ballot_num }}{% endblock %}

{% block subbreadcrumbs %}
<li><a href="{% url ballots.views.choose_riding_to_verify %}">Choose Riding to Verify</a></li>
<li><a href="{% url ballots.views.verify_riding ballot.poll.riding.id %}">Conflicted Ballots</a></li>
<li>View Ballot {{ ballot.ballot_num }}</li>
{% endblock %}

{% block content %}
<p>Poll: {{ballot.poll}}</p>
<p>State: {{ballot.get_state_display}}</p>
<p>Vote: {{ballot.vote}}</p>
{% endblock %}
